---
- hosts: all
  sudo: yes
  tasks:
    - command: rm -rf /tmp/benchmarker
      args:
        removes: /tmp/benchmarker
    - shell: rsync -aL --delete /tmp/isucon4/qualifier/benchmarker /tmp/
    - command: chown -R isucon:isucon /tmp/benchmarker
    - name: 'fix Makefile'
      lineinfile: >-
        dest='/tmp/benchmarker/Makefile'
        state=present 
        regexp='{{ item.regexp }}'
        line='{{ item.line }}'
        with_items:
          - regexp: '^GIT_COMMIT=.*' 
            line: 'GIT_COMMIT=""'
          - regexp: '-X main.GIT_COMMIT \"${GIT_COMMIT}\" \' 
            line: '-X main.GIT_COMMIT=\"${GIT_COMMIT}\" \'
          - regexp: '-X github.com/isucon/isucon4/qualifier/benchmarker/user.DummyUsersTSVMD5 \"${DUTMH}\" \'
            line: '-X github.com/isucon/isucon4/qualifier/benchmarker/user.DummyUsersTSVMD5=\"${DUTMH}\" \'
          - regexp: '-X github.com/isucon/isucon4/qualifier/benchmarker/user.DummyUsersUsedTSVMD5 \"${DUUTMH}\" \'
            line: '-X github.com/isucon/isucon4/qualifier/benchmarker/user.DummyUsersUsedTSVMD5=\"${DUUTMH}\" \'
          - regexp: '-X github.com/isucon/isucon4/qualifier/benchmarker/user.DebugMode \"${debugmode}\" \'
            line: '-X github.com/isucon/isucon4/qualifier/benchmarker/user.DebugMode=\"${debugmode}\" \'
          - regexp: '-X main.DebugMode \"${debugmode}\" \'
            line: '-X main.DebugMode=\"${debugmode}\" \'
          - regexp: '-X main.SkipMetadataMode \"${skipmetadata}\"'
            line: '-X main.SkipMetadataMode=\"${skipmetadata}\"'
  
    - lineinfile: dest=/tmp/benchmarker/main.go state=present regexp='checkInstanceMetadata\(\)' line=''
    - name: build benchmarker
      command: /home/isucon/env.sh make release
      sudo_user: isucon
      ignore_errors: yes
      args:
        chdir: /tmp/benchmarker
    - command: mv /tmp/benchmarker/benchmarker /home/isucon/
      sudo_user: isucon
